name: Java CI

on:
  push:
    branches: [main]  # Kích hoạt workflow khi có thay đổi trên nhánh 'main'
  pull_request:
    branches: [main]  # Kích hoạt workflow khi có pull request đến nhánh 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Kiểm tra mã nguồn từ kho lưu trữ

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'  # Chọn phiên bản JDK phù hợp
        distribution: 'temurin'  # Chọn phân phối JDK

    - name: Build with Maven
      run: mvn clean install  # Chạy lệnh để dọn dẹp và xây dựng dự án

    - name: Run tests
      run: mvn test  # Chạy các bài kiểm thử với Maven

    - name: Upload test results
      if: success()  # Chỉ upload nếu các bước trước thành công
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: target/surefire-reports/*.xml  # Đường dẫn đến báo cáo kiểm thử
